name: Buildpipe
description: Dynamically generate Buildkite pipelines based on project changes
author: https://github.com/ksindi
requirements:
  - python3
  - pip3
configuration:
  properties:
    diff:
      type: string
    dynamic_pipeline:
      type: string
    log_level:
      type: string
  required:
    - dynamic_pipeline
