#!/bin/bash
set -euo pipefail

basedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

docker build $basedir -t buildpipe > /dev/null

docker run --rm --env-file <(env | grep BUILDKITE) buildpipe
