#!/bin/bash
set -euo pipefail

buildpipe_version="${BUILDKITE_PLUGIN_BUILDPIPE_VERSION:-0.9.0}"
is_test="${BUILDKITE_PLUGIN_BUILDPIPE_TEST_MODE:-false}"

if [[ "$is_test" == "false" ]]; then
  wget -O buildpipe https://github.com/jwplayer/buildpipe-buildkite-plugin/releases/download/v${buildpipe_version}/buildpipe-linux
fi

chmod +x buildpipe

./buildpipe
